use clap::Subcommand;
use eyre::{Result, bail};

use crate::paths;

#[derive(Debug, Subcommand)]
pub enum ConfigAction {
    /// Generate config.toml with documented defaults
    Init {
        /// Project name (used as prefix for AWS resources)
        #[arg(long, default_value = "temporal-dev")]
        name: String,
        /// AWS region
        #[arg(long, default_value = "eu-west-1")]
        region: String,
    },
}

pub fn config(action: ConfigAction) -> Result<()> {
    match action {
        ConfigAction::Init { name, region } => init(&name, &region),
    }
}

fn init(name: &str, region: &str) -> Result<()> {
    let path = paths::config_file();

    if path.exists() {
        bail!(
            "config.toml already exists at '{}' — refusing to overwrite",
            path.display()
        );
    }

    let content = CONFIG_TEMPLATE
        .replace("name = \"temporal-dev\"", &format!("name = \"{name}\""))
        .replace("region = \"eu-west-1\"", &format!("region = \"{region}\""));

    std::fs::write(&path, content)?;
    eprintln!("▸ wrote {}", path.display());
    eprintln!("  project: {name}");
    eprintln!("  region:  {region}");
    Ok(())
}

const CONFIG_TEMPLATE: &str = r#"# ─────────────────────────────────────────────────────────────────────────────
# Temporal DSQL Deploy — Configuration
# ─────────────────────────────────────────────────────────────────────────────
# Generated by `dsqld config init`.
# The CLI generates dev/.env from this file before every `dsqld dev` command.
# ─────────────────────────────────────────────────────────────────────────────

# ─── Project ─────────────────────────────────────────────────────────────────
# Top-level project metadata. The name is used as a prefix for AWS resources
# (DSQL cluster, DynamoDB tables).

[project]
name = "temporal-dev"                          # Project name (resource prefix)
region = "eu-west-1"                           # AWS region

# ─── Aurora DSQL Persistence ─────────────────────────────────────────────────
# DSQL has two cluster-wide constraints that drive this configuration:
#   1. Connection rate limit: 100 new connections/sec (sustained), 1000 burst
#   2. Connection limit: 10,000 concurrent connections per cluster
#
# The connection management stack has three layers:
#   Layer 1 — Reservoir: Pre-creates connections so Open() never blocks
#   Layer 2 — Rate coordination: DynamoDB-backed token bucket (100/sec budget)
#   Layer 3 — Slot leasing: DynamoDB-backed block allocation (10k limit)
#
# This repo exercises the full stack — all three layers are enabled by default.

[dsql]
identifier = ""                                # Populated by `dsqld infra apply` (DSQL cluster ID)
port = 5432                                    # DSQL port
user = "admin"                                 # IAM auth user
database = "postgres"                          # Database name

# Per-pod connection pool
# CRITICAL: max_idle_conns MUST equal max_conns to prevent pool decay.
# DSQL connections are expensive to create (rate-limited), so we never let
# idle connections close. The pool stays at max_conns permanently.
max_conns = 50                                 # Max open connections per pool
max_idle_conns = 50                            # Must equal max_conns
connection_timeout = "30s"                     # Per-connection creation timeout
max_conn_lifetime = "55m"                      # Under DSQL's 60-minute hard limit

# ─── Layer 1: Connection Reservoir ───────────────────────────────────────────
# Pre-creates connections in a background goroutine so driver.Open() returns
# instantly from a ready buffer.

[dsql.reservoir]
enabled = true                                 # Enable reservoir (recommended)
target_ready = 50                              # Matches max_conns — pool starts fully warmed
base_lifetime = "11m"                          # Well under DSQL's 60-min limit
lifetime_jitter = "2m"                         # Prevents thundering herd (effective: 10-12m)
guard_window = "45s"                           # Won't hand out connections about to expire
inflight_limit = 8                             # Max concurrent Open() calls to DSQL

# ─── Layer 2: Distributed Rate Limiting (DynamoDB) ───────────────────────────
# Coordinates the cluster-wide 100 connections/sec budget across all pods.

[dsql.rate_coordination]
enabled = true                                 # Enable distributed rate limiting
table_name = ""                                # DynamoDB table (derived: {project.name}-dsql-rate-limiter)
limit = 100                                    # DSQL sustained rate: 100 connections/sec

# Token bucket algorithm for rate coordination
[dsql.rate_coordination.token_bucket]
enabled = true                                 # Token bucket is the recommended algorithm
rate = 100                                     # Tokens per second (DSQL sustained rate)
capacity = 1000                                # Bucket capacity (DSQL burst capacity)

# ─── Layer 3: Distributed Connection Leasing (DynamoDB) ──────────────────────
# Coordinates the cluster-wide 10k connection limit across all pods.

[dsql.conn_lease]
enabled = true                                 # Enable connection leasing
table_name = ""                                # DynamoDB table (derived: {project.name}-dsql-conn-lease)
block_size = 100                               # Slots per block
block_count = 100                              # Total blocks (100 × 100 = 10k slots)
block_ttl = "3m"                               # TTL for crash recovery
renew_interval = "1m"                          # Block lease renewal frequency

# ─── Elasticsearch (Visibility Store) ────────────────────────────────────────
# Elasticsearch is the visibility store. DSQL is persistence only.

[elasticsearch]
host = "elasticsearch"                         # Hostname (Docker service name)
port = 9200                                    # HTTP port
scheme = "http"                                # Protocol (http for local dev)
version = "v8"                                 # Elasticsearch major version
index = "temporal_visibility_v1_dev"           # Visibility index name

# ─── Temporal ────────────────────────────────────────────────────────────────
# Temporal server configuration.

[temporal]
log_level = "info"                             # Log level (debug, info, warn, error)
history_shards = 4                             # Number of history shards (local dev)
image = "temporal-dsql-server:latest"          # Docker image for Temporal services

# ─── DynamoDB ────────────────────────────────────────────────────────────────
# DynamoDB table names for distributed rate limiting and connection leasing.
# Derived from project.name by `dsqld infra apply` if left empty.

[dynamodb]
rate_limiter_table = ""                        # Default: {project.name}-dsql-rate-limiter
conn_lease_table = ""                          # Default: {project.name}-dsql-conn-lease
"#;
