#!/usr/bin/env bash
set -euo pipefail

# Quick deployment script for ephemeral test environments
# This script automates the Terraform deployment with pre-configured variables

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"

# Configuration
PROJECT_NAME="${PROJECT_NAME:-temporal-test-$(date +%s)}"
REGION="${AWS_REGION:-eu-west-1}"
TEMPORAL_DSQL_PATH="${TEMPORAL_DSQL_PATH:-../temporal-dsql}"
BUILD_IMAGES="${BUILD_IMAGES:-true}"
TARGET_ARCH="${TARGET_ARCH:-$(uname -m)}"

# Normalize architecture names
case "$TARGET_ARCH" in
    x86_64|amd64) TARGET_ARCH="amd64" ;;
    aarch64|arm64) TARGET_ARCH="arm64" ;;
    armv7l|arm) TARGET_ARCH="arm" ;;
    *) echo "WARNING: Unknown architecture $TARGET_ARCH, using as-is" ;;
esac

echo "=== Deploying Temporal DSQL Test Environment ==="
echo "Project Name: $PROJECT_NAME"
echo "Region: $REGION"
echo "Build Images: $BUILD_IMAGES"
echo "Target Architecture: $TARGET_ARCH"
echo ""

# Step 1: Build and test Docker images (if requested)
if [ "$BUILD_IMAGES" = "true" ]; then
    echo "=== Step 1: Building and Testing Docker Images ==="
    if [ -d "$TEMPORAL_DSQL_PATH" ]; then
        echo "Running build script to create images for $TARGET_ARCH..."
        "$SCRIPT_DIR/build-temporal-dsql.sh" "$TEMPORAL_DSQL_PATH" "$TARGET_ARCH"
        echo ""
    else
        echo "WARNING: temporal-dsql path not found: $TEMPORAL_DSQL_PATH"
        echo "Skipping image build. Ensure temporal-dsql:latest image exists."
        echo "Set TEMPORAL_DSQL_PATH, TARGET_ARCH, or BUILD_IMAGES=false to skip this step."
        echo ""
    fi
fi

# Step 2: Check for required ACM ARNs
echo "=== Step 2: Validating ACM Certificates ==="
if [ -z "${CLIENT_VPN_SERVER_CERT_ARN:-}" ]; then
    echo "ERROR: CLIENT_VPN_SERVER_CERT_ARN environment variable not set"
    echo ""
    echo "Please set the ACM certificate ARNs:"
    echo "  export CLIENT_VPN_SERVER_CERT_ARN='arn:aws:acm:...'"
    echo "  export CLIENT_VPN_ROOT_CERT_ARN='arn:aws:acm:...'"
    echo ""
    echo "Or run the certificate helper first:"
    echo "  uv run dsql-deploy print-acm-arns"
    exit 1
fi

if [ -z "${CLIENT_VPN_ROOT_CERT_ARN:-}" ]; then
    echo "ERROR: CLIENT_VPN_ROOT_CERT_ARN environment variable not set"
    exit 1
fi

echo "✅ ACM certificates configured"
echo ""

# Step 3: Deploy Infrastructure
echo "=== Step 3: Deploying AWS Infrastructure ==="
# Navigate to Terraform directory
cd "$TERRAFORM_DIR"

# Initialize Terraform if needed
if [ ! -d ".terraform" ]; then
    echo "Initializing Terraform..."
    terraform init
fi

# Deploy infrastructure
echo "Deploying infrastructure..."
terraform apply \
    -var "project_name=$PROJECT_NAME" \
    -var "region=$REGION" \
    -var "client_vpn_server_certificate_arn=$CLIENT_VPN_SERVER_CERT_ARN" \
    -var "client_vpn_authentication_options=[{type=\"certificate-authentication\",root_certificate_chain_arn=\"$CLIENT_VPN_ROOT_CERT_ARN\"}]" \
    -auto-approve

# Export outputs
echo ""
echo "=== Step 4: Configuring Environment ==="
echo ""
echo "Extracting outputs..."
terraform output -json > "$PROJECT_ROOT/terraform-outputs.json"

# Extract key values
DSQL_ENDPOINT=$(terraform output -json dsql_vpc_endpoint_dns_entries | jq -r '.[0].dns_name')
VPN_ENDPOINT_ID=$(terraform output -raw client_vpn_endpoint_id)
VPC_ID=$(terraform output -raw vpc_id)
OPENSEARCH_ENDPOINT=$(terraform output -raw opensearch_collection_endpoint)

echo "DSQL Endpoint: $DSQL_ENDPOINT"
echo "VPN Endpoint ID: $VPN_ENDPOINT_ID"
echo "VPC ID: $VPC_ID"
echo "OpenSearch Endpoint: $OPENSEARCH_ENDPOINT"
echo ""

# Export VPN client configuration
echo "Exporting VPN client configuration..."
aws ec2 export-client-vpn-client-configuration \
    --client-vpn-endpoint-id "$VPN_ENDPOINT_ID" \
    --region "$REGION" \
    --output text > "$PROJECT_ROOT/client-vpn.ovpn"

echo "VPN configuration saved to: client-vpn.ovpn"
echo ""

# Generate .env file
echo "Generating .env file..."
cat > "$PROJECT_ROOT/.env" <<EOF
# Generated by deploy-test-env.sh on $(date)
TEMPORAL_BASE_IMAGE=temporal-dsql:latest
TEMPORAL_RUNTIME_IMAGE=temporal-dsql-runtime:dev

# Aurora DSQL via VPC Endpoint
TEMPORAL_SQL_HOST=$DSQL_ENDPOINT
TEMPORAL_SQL_PORT=5432
TEMPORAL_SQL_DATABASE=temporal
TEMPORAL_SQL_USER=temporal_admin
TEMPORAL_SQL_PLUGIN_NAME=dsql
TEMPORAL_SQL_TLS_ENABLED=true
TEMPORAL_SQL_SERVER_NAME=
TEMPORAL_SQL_CA_FILE=/etc/ssl/certs/ca-certificates.crt
TEMPORAL_HISTORY_SHARDS=512
TEMPORAL_SQL_MAX_CONNS=50
TEMPORAL_SQL_MAX_IDLE_CONNS=10

# DSQL-specific Snowflake ID generation
TEMPORAL_SQL_NODE_ID=1
TEMPORAL_SQL_ID_GENERATOR=snowflake
TEMPORAL_SQL_CONNECTION_TIMEOUT=30s
TEMPORAL_SQL_MAX_CONN_LIFETIME=1h
TEMPORAL_SQL_SSL_MODE=require

# Host-side secret files
TEMPORAL_SQL_PASSWORD_FILE_HOST=./secrets/dsql-password
TEMPORAL_OPENSEARCH_PASSWORD_FILE_HOST=./secrets/opensearch-password

# OpenSearch Serverless visibility endpoint (from Terraform)
TEMPORAL_OPENSEARCH_ENDPOINT=$OPENSEARCH_ENDPOINT
TEMPORAL_OPENSEARCH_USER=

# Temporal UI
TEMPORAL_UI_PORT=8080
EOF

echo ".env file created"
echo ""

echo "=== Deployment Complete! ==="
echo ""
echo "📋 Summary:"
echo "  • Project: $PROJECT_NAME"
echo "  • Region: $REGION"
echo "  • Architecture: $TARGET_ARCH"
echo "  • DSQL Endpoint: $DSQL_ENDPOINT"
echo "  • VPN Endpoint: $VPN_ENDPOINT_ID"
echo "  • Docker Images: $([ "$BUILD_IMAGES" = "true" ] && echo "Built for $TARGET_ARCH" || echo "Assumed existing")"
echo ""
echo "📁 Files Created:"
echo "  • terraform-outputs.json (Terraform metadata)"
echo "  • client-vpn.ovpn (VPN configuration)"
echo "  • .env (Docker Compose environment)"
echo ""

echo "=== Next Steps ==="
echo "1. Connect to VPN:"
echo "   sudo openvpn --config client-vpn.ovpn --daemon"
echo ""
echo "2. Set up secrets:"
echo "   mkdir -p secrets"
echo "   echo 'your-password' > secrets/dsql-password"
echo "   echo 'your-opensearch-password' > secrets/opensearch-password"
echo ""
echo "3. Build and start Temporal:"
echo "   docker compose build temporal"
echo "   docker compose up -d temporal temporal-ui"
echo ""
echo "4. When done, cleanup:"
echo "   cd terraform && terraform destroy -auto-approve"
