#!/usr/bin/env bash
set -euo pipefail

# Generate .env file from Terraform outputs
# This script reads terraform outputs and generates a .env file for Docker Compose

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"

# Check if terraform outputs exist
if [ ! -f "$TERRAFORM_DIR/terraform.tfstate" ]; then
    echo "ERROR: No Terraform state found. Run 'terraform apply' first." >&2
    exit 1
fi

# Navigate to Terraform directory
cd "$TERRAFORM_DIR"

# Extract outputs
DSQL_ENDPOINT=$(terraform output -json dsql_vpc_endpoint_dns_entries 2>/dev/null | jq -r '.[0].dns_name' || echo "")
VPN_ENDPOINT_ID=$(terraform output -raw client_vpn_endpoint_id 2>/dev/null || echo "")
VPC_ID=$(terraform output -raw vpc_id 2>/dev/null || echo "")
OPENSEARCH_ENDPOINT=$(terraform output -raw opensearch_collection_endpoint 2>/dev/null || echo "")

# Validate required outputs
if [ -z "$DSQL_ENDPOINT" ]; then
    echo "ERROR: Could not extract DSQL endpoint from Terraform outputs" >&2
    exit 1
fi

if [ -z "$OPENSEARCH_ENDPOINT" ]; then
    echo "ERROR: Could not extract OpenSearch endpoint from Terraform outputs" >&2
    exit 1
fi

# Generate .env content
cat <<EOF
# Generated by terraform-to-env.sh on $(date)
# Terraform outputs from VPC ID: $VPC_ID

# Base Temporal image inputs
TEMPORAL_BASE_IMAGE=temporal-dsql:latest
TEMPORAL_RUNTIME_IMAGE=temporal-dsql-runtime:dev

# Aurora DSQL via VPC Endpoint (from Terraform)
TEMPORAL_SQL_HOST=$DSQL_ENDPOINT
TEMPORAL_SQL_PORT=5432
TEMPORAL_SQL_DATABASE=temporal
TEMPORAL_SQL_USER=temporal_admin
TEMPORAL_SQL_PLUGIN_NAME=dsql
TEMPORAL_SQL_TLS_ENABLED=true
TEMPORAL_SQL_SERVER_NAME=
TEMPORAL_SQL_CA_FILE=/etc/ssl/certs/ca-certificates.crt
TEMPORAL_HISTORY_SHARDS=512
TEMPORAL_SQL_MAX_CONNS=50
TEMPORAL_SQL_MAX_IDLE_CONNS=10

# DSQL-specific Snowflake ID generation
TEMPORAL_SQL_NODE_ID=1
TEMPORAL_SQL_ID_GENERATOR=snowflake
TEMPORAL_SQL_CONNECTION_TIMEOUT=30s
TEMPORAL_SQL_MAX_CONN_LIFETIME=1h
TEMPORAL_SQL_SSL_MODE=require

# Host-side secret files (paths on your workstation)
TEMPORAL_SQL_PASSWORD_FILE_HOST=./secrets/dsql-password
TEMPORAL_OPENSEARCH_PASSWORD_FILE_HOST=./secrets/opensearch-password

# OpenSearch Serverless visibility endpoint (from Terraform)
# Use directly with IAM authentication or through aws-sigv4-proxy
TEMPORAL_OPENSEARCH_ENDPOINT=$OPENSEARCH_ENDPOINT
TEMPORAL_OPENSEARCH_USER=

# Temporal UI
TEMPORAL_UI_PORT=8080

# Terraform metadata (for reference)
# VPN_ENDPOINT_ID=$VPN_ENDPOINT_ID
# VPC_ID=$VPC_ID
EOF